version: '3.8'
services:
  db:
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 5
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1q2w3e4r!@#$
      MYSQL_DATABASE: smartphones_db
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/smartphones_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1q2w3e4r!@#$
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8081:8081"
    restart: on-failure


  frontend:
    build:
      context: ./ui
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  db-data: